# -*- coding: utf-8 -*-
"""FAQs and hero photography retrofitted onto the pre-2026 blog posts.

Kept separate from the original content modules so those stay untouched.
build.py merges this in by slug: RETROFIT[slug] = (faqs, hero).
"""

RETROFIT = {

"finolex-qr-code-scan-genuine": ([
 ("Does every Finolex wire box have a QR code?", "Genuine Finolex coils ship in printed cartons carrying a QR code alongside the batch details, size in sq mm, grade and coil length. If a carton has no code at all, or the code is on a pasted sticker rather than printed with the rest of the label, treat the coil as suspect and ask the shop for a sealed replacement."),
 ("What should happen when I scan a genuine Finolex QR code?", "The code should open Finolex's own official verification page, and the product details it shows — range, size and batch — should match what is printed on the carton in your hand. If it opens a look-alike website, a generic page with no product details, or reports the code as already used many times, do not pay for that coil."),
 ("Can a duplicate wire carry a QR code too?", "Yes, counterfeiters copy codes and reprint them. That is why the check is not whether a code exists but whether it scans to the brand's own domain and returns details matching the carton. Copied codes also lose sharpness when reprinted, so blurry or smudged printing is a strong warning sign."),
 ("Can I scan the code before paying?", "Yes, and you should. At Mount Cable you scan every box at your site before payment, because we work on pay on delivery. Any shop unwilling to let you scan a carton before you pay is telling you something important about the stock."),
 ("What if the wire is sold loose without a box?", "Then there is no QR code, no batch number and no way to verify anything. Loose or cut wire without a carton is the single easiest way for duplicate material to enter a house. Insist on sealed boxes for every coil, whatever the price difference."),
], ("electrician-scanning-qr-code-wire-coil.jpg", "Scanning the QR code on a wire carton to verify it is genuine before paying")),

"electrician-retailer-nexus-duplicate-wires": ([
 ("Why would an electrician recommend duplicate wire?", "Because duplicate wire carries a far larger commission for whoever sells and specifies it. Genuine branded wire runs on 3 to 5% margin, so there is little to share, whereas a convincing duplicate can carry several times that. The electrician is rarely the villain, but the incentive structure works against the homeowner."),
 ("How does duplicate wire reach a house on a with-material contract?", "On a with-material contract the contractor buys and the savings stay with him, so substituting a cheaper coil is invisible profit. The wire disappears inside the wall before anyone inspects it, and the homeowner has no bill in their own name to check against."),
 ("How do I protect myself without accusing my electrician?", "Buy the wire and switchgear yourself, in your own name, with your own bills, and let the electrician handle labour. It removes the temptation entirely without anyone having to have an awkward conversation, and it is the single most effective step a home builder can take."),
 ("Is a big showroom a guarantee of genuine stock?", "No. A large, well-fitted showroom is expensive to run, which is exactly why some carry duplicate lines alongside genuine ones — the premises legitimise the stock. Ask for the authorised dealer certificate for the brand, and verify each carton by QR at your site."),
 ("What is the clearest sign that a wire quote involves duplicate stock?", "A price far below the market band. Wires are a 3 to 5% margin business, so no genuine seller can go 15% or more below the going rate. Get a reference quote from an established distributor and treat any large gap as a specification difference, not a bargain."),
], ("shop-owner-explaining-wire-quality.jpg", "A shop owner explaining the difference between genuine and duplicate wire to a customer")),

"why-buy-finolex-90m-coils": ([
 ("Why is a 90 metre coil safer to buy than loose wire?", "Because a sealed 90m carton carries the brand's printing, batch number, grade and QR code, all of which can be verified at your site. Loose or cut wire has none of that, so there is no way to prove what you actually bought or to claim against it later."),
 ("Do shops ever sell short coils?", "Under-length coils are a known trick, and one that is almost impossible to detect once the wire is in the wall. A sealed factory carton from an authorised source is the practical protection, because the length is the manufacturer's responsibility rather than the counter's."),
 ("Is a 90 metre coil the standard size in India?", "Yes, 90m is the standard house wire pack and the size every electrician estimates in. Larger 180m and 300m coils are also made and work out slightly cheaper per metre, which is worth asking about when a single size needs four or more coils."),
 ("What should I check on the carton before paying?", "The size in sq mm, the grade such as FR or FRLS, the coil length, the batch number, print sharpness and alignment, and the QR code scanning to the brand's own site. Any sticker pasted over printed information deserves a question."),
 ("What do I do with leftover coils?", "Mount Cable picks up surplus material free of charge, so there is no reason to over-order in the first place. Order about 90% of your estimate and top up after the first floor is pulled — we deliver next day across Bangalore."),
], ("wire-coils-warehouse-electrical-distributor.jpg", "Sealed 90 metre wire coils stacked at an authorised distributor warehouse")),

"authorised-finolex-dealer-check": ([
 ("How do I know if a shop is an authorised dealer?", "Ask to see the authorisation certificate for that specific brand, and check that the name on it matches the shop's billing name. Authorised dealers keep it and are happy to show it. Hesitation, an expired certificate or a certificate in a different entity's name are all worth taking seriously."),
 ("Does buying from an authorised dealer cost more?", "Not meaningfully. Genuine wire is MRP-linked and runs on 3 to 5% margin, so authorised and unauthorised sellers of genuine stock quote within a few percent of each other. A much lower price generally means different stock, not a better deal."),
 ("Why does authorisation matter if the product looks the same?", "Because it decides what happens when something goes wrong. Warranty claims, replacements and batch traceability all run through the authorised channel. Product bought outside it may be genuine and still leave you with no route to a claim."),
 ("What paperwork should I get with my order?", "A proper GST invoice in your own name listing the brand, size, grade and quantity of every item. That invoice is what makes a warranty claim possible, and it is also what stops material bought for your house being billed to someone else."),
 ("Is Mount Cable an authorised distributor?", "Yes. Mount Cable India is one of the largest distributors of Finolex cables in India and an authorised multi-brand dealer, and we sell only sealed, QR-verifiable, warranty-backed stock. Ask us for the certificate at either showroom and we will show it."),
], ("electrical-shop-counter-happy-customer.jpg", "An authorised electrical dealer serving a customer at the counter in Bangalore")),

"house-wiring-wire-size-guide": ([
 ("What wire size should be used for lights and fans?", "1.0 or 1.5 sq mm is standard for light and fan circuits, protected by a 6A Curve B MCB. Use 1.5 sq mm where runs are long or where a circuit carries a large number of points, because voltage drop over distance rather than current is usually what governs."),
 ("Which wire size is needed for power sockets?", "2.5 sq mm for 16A power sockets and kitchen circuits, with a 16A Curve C MCB. Ordinary 6A socket points can run on 1.5 sq mm, but anything intended for a fridge, microwave or washing machine should be on 2.5 sq mm from the start."),
 ("What size wire for an air conditioner or geyser?", "4.0 sq mm on a dedicated circuit for a 1.5 ton air conditioner or a 3000W geyser, with a 20A Curve C MCB. A 1 ton unit or a 2000W geyser can use 2.5 sq mm on a short run. Long runs need checking for voltage drop, which can push the requirement up a size."),
 ("Can I use a smaller wire to save money?", "It is the most expensive saving in a house. An undersized concealed circuit runs warm every summer, ages its insulation prematurely, and can only be corrected by breaking finished walls. The difference between correct and undersized on a whole house is usually a few thousand rupees."),
 ("How do I check the right size for my own circuits?", "Use the free wire size calculator, which takes the load, the run length and the supply type, sizes the cable on current capacity and then re-checks it against voltage drop. It also suggests the matching MCB rating."),
], ("electricians-installing-conduit-ceiling.jpg", "Electricians running conduit and wiring through a house under construction in Bangalore")),

"finolex-wire-price-bangalore": ([
 ("What is the price of Finolex wire in Bangalore?", "Approximately ₹1,950 to ₹2,250 for a 1.5 sq mm FR 90m coil, ₹3,150 to ₹3,650 for 2.5 sq mm and ₹4,700 to ₹5,400 for 4.0 sq mm in 2026. These are reference bands that move with copper prices, so WhatsApp 88676 76700 for today's exact rate."),
 ("How do I buy Finolex wire at distributor rate?", "Buy directly from an authorised distributor rather than through a contractor's with-material contract, order the whole house in one go rather than floor by floor, and ask for a written quote with a validity period so the rate is held while you build."),
 ("Why do Finolex prices change so often?", "Because a wire coil is mostly copper, and copper is an internationally traded commodity priced in dollars. Rates track the copper market and the rupee-dollar exchange rate, with periodic manufacturer MRP revisions resetting the band."),
 ("Is a big discount on Finolex wire genuine?", "Rarely. Wires run on 3 to 5% dealer margin, so a discount of 15% or more is not a discount but a different product — usually copper shortfall, short coil length or an outright duplicate. Ask to see the carton, the batch and the QR before paying."),
 ("Can I use your quote to check another shop's price?", "Yes, and we encourage it. Send your list to 88676 76700, get an itemised quote within 60 minutes, and use it as your reference price anywhere. There is no obligation to buy from us."),
], ("contractor-checking-price-list-phone.jpg", "A customer checking an itemised wire price quotation on WhatsApp")),

"fr-vs-frls-vs-finolex-ultra": ([
 ("What is the difference between FR and FRLS wire?", "FR is flame retardant, meaning the insulation resists catching fire and slows flame spread. FRLS is flame retardant low smoke, which additionally emits far less smoke and corrosive gas while burning. In a fire, smoke is what disables people before flame does, which is why FRLS matters in enclosed homes."),
 ("Is FRLS wire worth the extra cost?", "It typically costs around 8 to 12% more per coil, which on a whole house is a modest sum against a meaningful safety difference. It is most worth it in flats, in stairwells and corridors, and anywhere escape routes are enclosed."),
 ("Where should FRLS wire be used in a house?", "Ideally throughout, and at minimum on circuits running through enclosed spaces, corridors, stairwells and shafts where smoke would accumulate. Many builders use FRLS on the main and common runs and standard FR on peripheral circuits."),
 ("What does Finolex Ultra offer over standard ranges?", "The premium ranges use higher-specification insulation compounds with better heat resistance and lower smoke emission, and are aimed at installations wanting the highest specification. For most homes, good FR or FRLS from a genuine source covers the requirement well."),
 ("Does the grade affect the wire size I need?", "No. Grade affects fire behaviour and smoke, not current-carrying capacity, so sizing is determined by load and run length regardless of whether you choose FR or FRLS. Use the wire size calculator to confirm the size, then choose the grade separately."),
], ("electrician-hands-stripping-wire-closeup.jpg", "Close-up of house wire insulation being stripped, showing conductor and grade")),

"electrical-checklist-building-house-bangalore": ([
 ("What electrical items do I need to buy for a new house?", "Conduit and accessories, house wire in 1.0 to 6.0 sq mm plus earth wire, modular switches and sockets, MCBs, an RCCB, a distribution board, earthing electrode and strip, fans, lights, and special cables for the pump, LAN and TV. They are bought in that order because conduit precedes plastering and switches come last."),
 ("When should each item be bought during construction?", "Conduit and mounting boxes before plastering, wire after plastering and before painting, and switches, plates, MCBs, the distribution board, fans and lights after painting. Buying the visible layer early means three months of dust and scratches on site."),
 ("What is most often left out of a contractor's list?", "Earth wire quantity, adequate 4.0 sq mm for air conditioner and geyser circuits, the RCCB, and network cabling. All four are cheap during construction and expensive or impossible to add afterwards."),
 ("Should I buy the material or let the contractor?", "Buy the wire and switchgear yourself in your own name with your own bills, and let the contractor handle labour and small consumables. Those are the high-value, quality-critical items, and they are the ones that disappear into walls unverified."),
 ("How do I get an exact price for the whole list?", "Use the material list builder to assemble it, or WhatsApp a photo of your contractor's estimate to 88676 76700. You will get an exact itemised quote within 60 minutes, with free next-day delivery across Bangalore and payment on delivery."),
], ("builder-architect-site-electrical-planning.jpg", "A builder and architect going through the electrical material checklist at a site in Bangalore")),

"how-to-identify-original-finolex-wire": ([
 ("How can I tell if Finolex wire is original?", "Check that the carton is sealed and factory printed with sharp, correctly aligned text, that the size, grade, length and batch number are all present, that the QR code scans to Finolex's own site and returns matching details, and that the price is within the normal market band rather than far below it."),
 ("Does genuine Finolex wire have markings on the insulation?", "Yes, genuine house wire carries repeating printed markings along the insulation identifying the brand, size and standard. On duplicates this printing is often uneven, faint, incorrectly spaced or missing altogether, so it is worth unrolling a metre and looking closely."),
 ("Can I check the copper itself?", "Cut a short piece and look at the conductor end. Genuine electrolytic-grade copper is bright and uniform with consistent strand count and thickness. Duplicates commonly show fewer or thinner strands, a dull or reddish tone, or visible variation along the length."),
 ("Is a low price by itself proof of a fake?", "It is the strongest single indicator. Because genuine wire runs on 3 to 5% margin, no authorised seller can go far below the market band. A price 15% or more under the going rate almost always means copper shortfall, short length or counterfeit stock."),
 ("What should I do if I suspect the wire delivered is not genuine?", "Do not let it go into the wall. Stop the work, keep the carton and the invoice, and raise it with the seller immediately. With pay on delivery and QR verification at your site, the check should happen before payment rather than after installation."),
], ("shop-owner-explaining-wire-quality.jpg", "Examining the copper conductor of a house wire to check it is genuine")),

"how-to-identify-duplicate-rr-kabel-wire": ([
 ("How do I check whether RR Kabel wire is genuine?", "Buy sealed cartons only, check the printing on the carton for sharpness and correct alignment, confirm the size, grade, length and batch are all present, scan the QR where provided, and inspect the repeating markings printed along the insulation for even spacing and clarity."),
 ("What does duplicate RR Kabel wire usually get wrong?", "Most commonly the copper: fewer or thinner strands than the marked sq mm, which is invisible once installed and shows up years later as a warm circuit. Carton printing quality and insulation marking consistency are the next most common giveaways."),
 ("Is loose RR Kabel wire safe to buy?", "No. Without a carton there is no batch number, no QR, no length guarantee and no warranty route. Loose or cut wire is the easiest way for duplicate material to enter a house, whatever assurance the counter offers."),
 ("How much below market price should worry me?", "More than about 8% below the market band on a branded coil. Wires run on 3 to 5% dealer margin, so deep discounts are not competitive pricing, they are a different product. Get a reference quote and compare like for like on grade and coil length."),
 ("Where can I buy genuine RR Kabel wire in Bangalore?", "From an authorised dealer that will show you the certificate and let you QR-verify each carton before you pay. Mount Cable stocks RR Kabel at both showrooms with free next-day delivery across Bangalore and payment on delivery."),
], ("electrician-scanning-qr-code-wire-coil.jpg", "Verifying a wire carton by scanning its QR code before purchase")),

"how-to-identify-duplicate-polycab-wire": ([
 ("How common is duplicate Polycab wire?", "Popular brands are copied most, and Polycab's market position makes it a frequent target. That is an argument for buying through an authorised channel rather than avoiding the brand, since the counterfeits exist precisely because the genuine product is in demand."),
 ("What are the quickest checks on a Polycab carton?", "Sealed carton with factory printing rather than a pasted label, sharp and correctly aligned text, size, grade, coil length and batch number all present, and a QR that scans to Polycab's own domain and returns details matching the box in your hand."),
 ("How do I check the copper inside?", "Cut a short length and examine the conductor. Count the strands and look at their uniformity and colour. Duplicates commonly run under the marked cross-section, using fewer or thinner strands, which cannot be seen once the wire is inside conduit."),
 ("Does a shop selling genuine Polycab ever discount heavily?", "Not deeply. At 3 to 5% margin there is very little room, so 5 to 8% off on a large order is aggressive but plausible while 15% or more is not. Treat an outlier quote as a specification question rather than a bargain."),
 ("What paperwork protects me?", "A GST invoice in your own name listing brand, size, grade and quantity for every item. Without it a warranty claim is very difficult, and material bought for your house can end up billed elsewhere."),
], ("electrical-shop-counter-happy-customer.jpg", "A customer inspecting a sealed wire carton at an authorised electrical counter")),

"how-to-identify-duplicate-v-guard-wire": ([
 ("How do I verify V-Guard wire is genuine?", "Insist on sealed cartons, check print sharpness and alignment on the label, confirm size, grade, length and batch are printed rather than stickered, scan the QR where available, and look at the repeating markings along the insulation for even spacing."),
 ("What is the most common giveaway on duplicate V-Guard wire?", "Insulation printing that is faint, uneven or incorrectly spaced, combined with a carton whose print quality does not match the rest of the packaging. Copied artwork loses definition each time it is reprinted."),
 ("Should I weigh the coil?", "A significantly light coil suggests copper shortfall or short length, and experienced buyers do check. It is a useful cross-check rather than a definitive test, since packaging weight varies — the more reliable route is a sealed carton from an authorised source."),
 ("Is V-Guard wire cheaper than other major brands?", "V-Guard often sits slightly below Finolex and Polycab, but the honest spread between major brands on comparable grades is single-digit percent. A quote far below that spread indicates a different product rather than a cheaper brand."),
 ("Where can I buy genuine V-Guard wire in Bangalore?", "From an authorised dealer who will show the certificate and let you verify each carton at your site before payment. Mount Cable stocks V-Guard with free next-day delivery across Bangalore and pay-on-delivery terms."),
], ("wire-coils-warehouse-electrical-distributor.jpg", "Branded wire coils stored at an authorised distributor in Bangalore")),

"how-to-identify-duplicate-kei-wire": ([
 ("What should I check first on a KEI wire carton?", "That it is factory sealed and factory printed, with size in sq mm, grade, coil length and batch number all present in sharp, correctly aligned text. A pasted sticker covering any of that information is the most common single warning sign."),
 ("How do I confirm the copper is full specification?", "Cut a short piece and inspect the conductor end for strand count, strand thickness and uniform bright colour. Copper shortfall is the defining feature of most duplicate wire, and it is completely invisible once the coil is inside the wall."),
 ("Does KEI wire carry a verification code?", "Where the brand provides a QR or verification code, scan it and confirm it opens the manufacturer's own domain and returns details matching the carton. A code opening a generic page, a look-alike site or reporting repeated prior use should stop the purchase."),
 ("Is duplicate wire actually dangerous, or just poor value?", "Genuinely dangerous. Under-specified copper cannot carry its marked current, so the cable runs hot under normal household load, its insulation ages rapidly, and the failure mode is a fire inside a wall. It is not simply a quality compromise."),
 ("How do I get a reference price for KEI wire?", "WhatsApp your list to 88676 76700 for an itemised quote within 60 minutes and use it as your reference band, whether or not you buy from us. A competing quote far below that band deserves a close look at the carton."),
], ("electrician-hands-stripping-wire-closeup.jpg", "Inspecting the copper conductor of a house wire for full specification")),

"how-to-identify-duplicate-anchor-wire": ([
 ("How do I verify Anchor by Panasonic wire?", "Buy sealed cartons only, check that carton printing is sharp and correctly aligned with size, grade, length and batch all present, scan any QR to confirm it resolves to the manufacturer's own site, and inspect the repeating insulation markings for even spacing and clear definition."),
 ("What do counterfeit Anchor cartons usually get wrong?", "Colour reproduction and print definition. Copied artwork drifts in shade and loses sharpness, so logos and small text look slightly soft or misaligned. Compare against a carton you know is genuine if you have one to hand."),
 ("Does the Panasonic association make counterfeits less likely?", "No. Recognisable branding increases the incentive to copy, not decrease it. The protection is the purchase channel — an authorised dealer, a sealed carton, a proper invoice and verification at your site before you pay."),
 ("Can an electrician tell duplicate wire by handling it?", "An experienced electrician often notices insulation that feels different, strands that behave oddly when stripped, or a coil that seems light. It is a useful signal but not proof, because good duplicates are made to feel right. Verification at the carton is the reliable check."),
 ("What is the safest way to buy?", "Order in your own name from an authorised distributor, take a GST invoice listing every item by brand, size and grade, verify each carton by QR at your site, and pay only after that. Mount Cable works on exactly that basis."),
], ("happy-customer-receiving-electrical-order.jpg", "A customer receiving sealed cartons of electrical material at their home")),

"how-to-identify-duplicate-orbit-wire": ([
 ("How do I check Orbit wire is genuine?", "Look for a sealed, factory-printed carton with the size, grade, coil length and batch number clearly present, sharp print with no misalignment, and consistent repeating markings along the insulation. Avoid loose or cut wire entirely, since it carries none of these."),
 ("Are smaller brands copied as often as the big ones?", "Less often in absolute terms, but the checks matter just as much, because smaller brands sometimes have thinner verification infrastructure and fewer buyers who know what the genuine packaging looks like. Buying through an authorised channel does more work here, not less."),
 ("What is the single most reliable test?", "The conductor. Cut a short length and examine strand count, strand thickness and colour uniformity against the marked cross-section. Copper shortfall is what makes a duplicate cheap and what makes it dangerous."),
 ("Should price alone decide the brand?", "No. On comparable grades the honest spread between reputable brands is single-digit percent, so a large price gap points to a specification difference rather than a bargain. Choose a brand your electrician knows and your distributor stocks deeply, then verify the stock."),
 ("Where can I compare brands before buying?", "The brand selector and the wire price comparison guide put the major options side by side, and a reference quote from 88676 76700 gives you the current honest band for your specific list."),
], ("shop-owner-explaining-wire-quality.jpg", "Comparing wire samples at an electrical counter before buying")),

"how-to-identify-duplicate-havells-wire": ([
 ("How do I identify duplicate Havells wire?", "Check for a sealed factory carton with sharp, aligned printing showing size, grade, coil length and batch, scan any verification code to confirm it resolves to the brand's own site with matching details, and inspect the insulation markings along a metre of wire for even spacing and clarity."),
 ("Why are popular wire brands copied so often?", "Because demand makes the counterfeit easy to sell and the margin large. Genuine wire earns the seller 3 to 5%, while a convincing duplicate can earn several times that, which is why a deep discount is a warning rather than an opportunity."),
 ("Does a shop's size or appearance indicate genuineness?", "No. Large showrooms are expensive to run, which is part of why some carry duplicate lines alongside genuine stock — the premises make the product look credible. Ask for the brand authorisation certificate instead."),
 ("How do I verify at my site rather than at the shop?", "Buy on pay-on-delivery terms so the material arrives before money changes hands, then scan each carton and check the printed details against the invoice. Anything that does not verify goes back on the vehicle."),
 ("What happens if I have already installed suspect wire?", "Keep the cartons and the invoice and raise it with the seller immediately. If the wire is concealed and cannot be verified, an electrician can at least check circuit temperatures under load and confirm that the installed sizes match the design."),
], ("electrician-testing-socket-multimeter.jpg", "An electrician testing an installed circuit with a multimeter")),

"how-to-identify-duplicate-anchor-switches": ([
 ("How do I spot a duplicate Anchor Penta or Roma switch?", "Check the moulding for flash, seams that do not meet cleanly and slightly soft edges, compare the print quality of the branding on the module, feel the switch action for a crisp defined click rather than a vague one, and confirm the packaging is sealed with sharp printing."),
 ("Do duplicate switches actually fail?", "Yes, and predictably. The contact material inside decides how many thousand operations a switch survives, and counterfeits economise there because it is invisible. The result is a switch that becomes loose, warm or intermittent within a couple of years."),
 ("Is a warm switch plate a sign of a fake?", "It is a sign of a poor connection or an undersized contact, both of which are more common in counterfeit modules. A warm switch or socket should be investigated by an electrician regardless of brand, because it is an early warning of a fault."),
 ("How can I check before the switches are installed?", "Buy in sealed boxes, open one and compare it against a module you know is genuine, look at print sharpness and moulding consistency, and operate the switch several times. Switches are bought at the end of a build, so there is time to check them properly."),
 ("Where should I buy modular switches?", "From an authorised dealer, in sealed boxes, with an invoice naming the brand and series. Mount Cable stocks the main modular ranges at both showrooms with free next-day delivery across Bangalore."),
], ("woman-homeowner-choosing-modular-switches.jpg", "A homeowner examining modular switch modules on a showroom display board")),

"how-to-identify-duplicate-gm-switches": ([
 ("What are the tell-tale signs of duplicate GM modular switches?", "Moulding flash and uneven seams, branding print that looks soft or slightly off in colour, plates that do not sit flush in the frame, a switch action that feels loose or gritty, and packaging with lower print quality than the product warrants."),
 ("Do duplicate switches fit genuine plates and boxes?", "Often approximately, which is part of the problem. Small differences in module width leave visible gaps or require force, and a module that has to be forced into a frame is already stressed before it is ever switched."),
 ("Why does the switch mechanism matter so much?", "Because it is operated thousands of times over a house's life. Genuine modules use contact materials and mechanisms rated for that duty; counterfeits save money precisely there, so the action degrades and the contact resistance rises, which is what makes a switch run warm."),
 ("Can I check a switch without installing it?", "Yes. Operate it twenty or thirty times and feel whether the action stays consistent, inspect the moulding under good light, and compare the module against a known genuine one. Buy in sealed boxes so you are checking factory product."),
 ("What should the invoice say?", "The brand, the series name and the exact module type for each item. A vague invoice line makes a warranty claim difficult and makes it impossible to prove later what you were actually supplied."),
], ("happy-electrician-installing-modular-switch.jpg", "An electrician fitting a modular switch plate in a newly built home")),

"how-to-identify-duplicate-lisha-switches": ([
 ("How do buyers usually get fooled on modular switches?", "By choosing on appearance and price, since the visible plate is easy to copy convincingly while the contact material inside is invisible. The switch that looks identical in the shop is the one that becomes loose and warm two years later."),
 ("What should I inspect on a Lisha module before buying?", "Moulding quality with no flash or misaligned seams, sharp branding print, a firm and consistent switch action, correct module width so it seats flush in the frame, and sealed packaging with good print quality."),
 ("Is a cheaper switch range the same as a duplicate?", "No, and the distinction matters. A genuine entry-level range is honestly built to a price and will state its rating. A duplicate imitates a higher range while quietly economising on the parts that carry current. One is a budget choice, the other is a safety risk."),
 ("How many switch points does a house need?", "Around 60 to 90 for a 2BHK and 100 to 150 for a 3BHK. Beyond that, extra points are usually contractor revenue rather than convenience — though a few extra sockets in the kitchen and beside the bed are worth having."),
 ("When should switches be bought and fitted?", "At the very end, after painting. Only the mounting boxes go in early during the conduit stage. Modular plates scratch easily, and months on a dusty site does them no favours."),
], ("homeowner-electrician-discussing-switchboard.jpg", "A homeowner and electrician discussing switch board positions during a build")),

"how-to-identify-duplicate-legrand-switches": ([
 ("How do I verify a Legrand Myrius or Arteor switch is genuine?", "Check the moulding for clean seams and no flash, confirm the branding print is sharp and correctly positioned, feel for the precise switch action these ranges are known for, verify the module seats flush in the frame, and buy in sealed boxes with a proper invoice naming the series."),
 ("Are premium switch ranges copied more than budget ones?", "Yes, because the price gap makes the counterfeit profitable. A duplicate of a premium range can be produced at entry-level cost and sold near premium price, which is exactly why the checks matter most on the ranges you are paying most for."),
 ("What does a genuine premium switch feel like?", "Consistent and defined, with the same action on the first operation and the thousandth. Vagueness, a gritty feel, or an action that varies between modules in the same box are all reasons to question the stock."),
 ("Should the plates and modules come from the same range?", "Yes. Module widths and frame dimensions are designed as a system within a series, so mixing ranges or brands produces gaps, forced fits and uneven plates. It also splits warranty responsibility."),
 ("Where can I buy genuine Legrand switches in Bangalore?", "From an authorised dealer who can show the certificate and supply sealed boxes with an invoice naming the series. Mount Cable stocks Legrand alongside the other major modular ranges at both showrooms."),
], ("woman-homeowner-choosing-modular-switches.jpg", "Premium modular switch ranges displayed at an electrical showroom in Bangalore")),

"how-to-identify-duplicate-schneider-switches": ([
 ("How do I check a Schneider Livia or Zencelo switch?", "Inspect the moulding for clean, well-finished edges and no flash, check branding print sharpness and placement, operate the switch to confirm a firm consistent action, confirm the module seats flush without force, and insist on sealed boxes with an invoice naming the exact series."),
 ("What is usually wrong with a counterfeit premium switch?", "The parts you cannot see. Contact material and the switching mechanism determine how many operations the switch survives and how much resistance builds at the contact, and both are economised in counterfeits. Externally the copy can be very close."),
 ("Does a genuine switch cost much more than a fake?", "Enough that the fake is worth making. If a premium series is being offered at a price close to an entry range, that gap is the answer — no authorised seller can discount a premium modular range that far."),
 ("Can I mix Schneider switches with another brand's plates?", "Not reliably. Module widths and frame dimensions differ between manufacturers, so mixing leaves gaps or requires force, and a forced module is stressed before it is ever used. Keep plates and modules within one series."),
 ("What should I do if a new switch feels loose?", "Do not install it. A new module should feel firm and consistent from the first operation. Raise it with the seller while the box, the invoice and the rest of the batch are all still available for comparison."),
], ("happy-electrician-installing-modular-switch.jpg", "Fitting a premium modular switch into a wall plate in a Bangalore home")),

"how-to-identify-duplicate-greatwhite-switches": ([
 ("How do I tell a genuine Greatwhite Fiana or Myrah switch from a duplicate?", "Look for clean moulding with no flash or misaligned seams, sharp and correctly placed branding, a firm consistent switch action, a module that seats flush in the frame without force, and sealed packaging with good print quality."),
 ("Do duplicates copy the packaging as well?", "Usually they try, and print quality is where they fall short. Copied artwork loses definition and drifts in colour with each reprint, so logos and small text look slightly soft. Comparing against a box you know is genuine is the quickest check."),
 ("Why do counterfeit switches run warm?", "Because the contact material inside is under-specified, so resistance at the contact is higher than it should be and rises further as the mechanism wears. A warm switch or socket plate is an early fault signal that should be investigated immediately."),
 ("Is it worth matching switches and switchgear from one brand?", "It is convenient and keeps warranty responsibility in one place, and several brands including Greatwhite sell both. For switchgear specifically the more important point is that MCBs and the distribution board come from the same family."),
 ("How should switches be bought?", "In sealed boxes, from an authorised dealer, with an invoice naming the brand, series and module type. Buy them at the end of the build, after painting, so they are not damaged on site."),
], ("electrical-shop-counter-happy-customer.jpg", "Sealed boxes of modular switches at an authorised electrical dealer")),

"how-to-identify-duplicate-legrand-mcb": ([
 ("How do I check whether a Legrand MCB or RCCB is genuine?", "Buy in sealed boxes, confirm the printing is sharp and correctly aligned, check that the breaking capacity in kA is clearly marked, inspect the moulding for flash or misaligned seams, feel for a firm defined toggle action, and scan the verification code where the brand provides one."),
 ("Why is a counterfeit MCB more dangerous than a counterfeit switch?", "Because its whole purpose is to act during a fault, and a counterfeit's trip characteristics and breaking capacity are unverified. It may click convincingly in normal use and do nothing when a real fault current arrives, which is the one moment it matters."),
 ("What breaking capacity should a domestic MCB have?", "10kA is standard for Indian domestic MCBs, with some cheaper genuine ranges at 6kA. The figure is printed on the device, so check it. On a counterfeit the printed rating is simply a number with nothing behind it."),
 ("Does a duplicate RCCB still trip?", "It may trip at some current, but not reliably at the rated 30mA sensitivity or within the required time, which is precisely what determines whether a person survives a shock. An RCCB is the one device in a house that protects people rather than wiring."),
 ("Where should switchgear be bought?", "Only from an authorised distributor, in sealed boxes, with an invoice naming the brand and exact device type. Switchgear is the category where the price saving is smallest and the consequence of failure largest."),
], ("electrician-installing-mcb-distribution-board.jpg", "MCBs and an RCCB being installed in a home distribution board")),

"how-to-identify-duplicate-indo-asian-mcb": ([
 ("How do I identify a duplicate MCB?", "Check that the box is sealed and printed sharply, that the current rating, trip curve and breaking capacity in kA are all clearly marked, that the moulding has no flash and the seams meet cleanly, and that the toggle action is firm and defined rather than vague or rattly."),
 ("What is the risk of a fake breaker in a distribution board?", "It looks and behaves normally right up until a real fault, at which point it may fail to interrupt the current. The failure mode is a fire that nobody traces back to a component costing a few hundred rupees, which is why this is the worst possible place to economise."),
 ("Does the trip curve appear on genuine MCBs?", "Yes. Genuine breakers mark the curve, usually B or C, alongside the current rating, because it determines the device's behaviour under inrush. Missing or inconsistent curve marking is a serious warning sign."),
 ("Should I replace MCBs I suspect are counterfeit?", "Yes, and promptly. Replacement costs a few hundred rupees per device against a protection function that either works or does not. Have an electrician swap them for genuine devices of the correct rating and curve from an authorised source."),
 ("How do I choose the right MCB rating?", "The rating must match the cable, not the appliance, because the breaker protects the wiring. The free MCB selector takes the circuit type, load and installed cable size and returns the correct rating and curve, and warns if the cable is undersized."),
], ("electrician-installing-mcb-distribution-board.jpg", "Checking MCB markings and breaking capacity before installation")),

"where-to-buy-original-finolex-wires-bangalore": ([
 ("Where can I buy original Finolex wire in Bangalore?", "From an authorised distributor who will show you the dealer certificate, supply sealed QR-verifiable cartons, and give a GST invoice in your name. Mount Cable India is one of the largest Finolex distributors in the country, with showrooms in Jayanagar and Chickpete."),
 ("What should I insist on when buying?", "Sealed cartons rather than loose wire, a GST invoice in your own name listing brand, size, grade and quantity, the ability to scan each QR at your site before paying, and a clear replacement policy if a coil is short or faulty."),
 ("Do you deliver across Bangalore?", "Yes, free next-day delivery across Bangalore and often the same day, with no minimum order. You inspect and QR-verify the material at your site and then pay in cash, UPI, card or bank transfer."),
 ("How do I know the price is fair?", "WhatsApp your list to 88676 76700 for an itemised quote within 60 minutes and use it as your reference band. Genuine wire runs on 3 to 5% margin, so any competing quote far below that band is a different product rather than a better deal."),
 ("What if I order more than I need?", "We pick up surplus material free of charge. That means there is no reason to over-order — buy about 90% of your estimate and top up as the work progresses."),
], ("delivery-van-electrical-materials.jpg", "Free next-day delivery of genuine electrical material to a home in Bangalore")),

"finolex-vs-polycab-vs-rr-kabel-vs-kei-wire-comparison": ([
 ("Which is the best house wire brand in India?", "All four of Finolex, Polycab, RR Kabel and KEI use electrolytic-grade copper and meet the same IS standards, so on the fundamentals they are closely comparable. The choice that actually affects your house is whether the coil is genuine, correctly sized and properly installed."),
 ("How much do prices differ between these brands?", "Single-digit percent on comparable grades, with the bands overlapping heavily. A 1.5 sq mm FR 90m coil sits roughly between ₹1,850 and ₹2,250 across all four. Any quote far outside that band signals a different grade, a different coil length or duplicate stock."),
 ("What actually differs between the major wire brands?", "Premium insulation formulations and their names, availability of 180m and 300m coils, colour range and batch-to-batch consistency, and local availability and replacement speed. The last of these usually matters more in practice than the brand name."),
 ("Should I use one brand throughout the house?", "It is simpler for matching colours on later extensions and keeps warranty in one place, and there is no technical reason to mix. Choose the brand your electrician knows and your local distributor stocks deeply."),
 ("How do I compare quotes for different brands fairly?", "Compare the same grade, FR against FR, compare per metre rather than per coil since lengths differ, and check the size mix is identical — a cheaper total often means less 4.0 sq mm, which is a specification change rather than a saving."),
], ("wire-coils-warehouse-electrical-distributor.jpg", "House wire coils from multiple major brands stocked at a Bangalore distributor")),

"house-wiring-cost-bangalore-2026": ([
 ("How much does it cost to wire a house in Bangalore?", "For material, approximately ₹90,000 to ₹1,90,000 for a 2BHK and ₹1,50,000 to ₹3,00,000 for a 3BHK depending on specification, with premium builds going higher. Wiring labour is charged separately, usually per point or as a percentage of material."),
 ("What drives the cost difference between two similar houses?", "Mostly the modular switch range, which can swing the total by more than a lakh on a large house. After that, wire grade, the number of points, the number of air conditioner circuits and the distance from the meter to the distribution board."),
 ("Is wiring labour included in these figures?", "No. These are material costs. Ask your contractor to quote labour as a separate line so you can compare quotes properly, and so a with-material contract does not hide the material substitution that is common in this trade."),
 ("How can I reduce the cost without compromising safety?", "Choose a more modest switch range, trim the point count to what you will genuinely use, and buy the material yourself at distributor rates. Never economise on wire size for air conditioner and geyser circuits, on the RCCB, or on earthing."),
 ("How do I get an accurate figure for my own house?", "Run the house wiring cost calculator for a planning band, then send your list or drawing to 88676 76700 for an exact itemised quote within 60 minutes."),
], ("happy-homeowner-couple-new-house-wiring.jpg", "Homeowners in their newly built house planning the electrical work")),

"best-modular-switch-brands-india-2026": ([
 ("Which modular switch brand is best in India?", "For most homes any of the established brands bought genuine will serve well, and the choice comes down to the series rather than the badge. Premium series differ in contact material, switch action, plate finish and module range, all of which matter more than the brand name on the box."),
 ("How much should I budget per switch point?", "Roughly ₹180 to ₹350 per point for entry ranges, ₹350 to ₹700 for mid ranges, ₹700 to ₹1,500 for premium and ₹1,500 upwards for designer or touch ranges, including the module, its share of the plate and the mounting box."),
 ("What is the real difference between a cheap and an expensive switch?", "The contact material inside, which decides how many thousand operations the switch survives, and the mechanism, which decides whether the action stays crisp. Plate material, module range and colour consistency across batches also improve with tier."),
 ("When do I have to choose the switch brand?", "Before wiring, because mounting box sizes and module widths differ between brands and the boxes fitted during the conduit stage commit you to a brand family. The plate colour and finish can be decided much later."),
 ("Are duplicate modular switches common?", "Yes, especially of premium ranges where the price gap makes copying profitable. Buy sealed boxes from an authorised dealer, check moulding and print quality, and operate the switch several times before accepting it."),
], ("woman-homeowner-choosing-modular-switches.jpg", "Modular switch ranges on display at an electrical showroom in Bangalore")),

"where-to-buy-genuine-electrical-products-bangalore": ([
 ("How do I find a genuine electrical shop in Bangalore?", "Ask for the authorised dealer certificate for the specific brands you want, check that it names the shop's billing entity, insist on sealed cartons and a GST invoice in your own name, and confirm you can scan and verify each item at your site before paying."),
 ("Is a bigger shop safer to buy from?", "Not automatically. Large premises are expensive to run, which is part of why some carry duplicate lines alongside genuine stock — the showroom lends credibility to the product. Authorisation, sealed packaging and site verification are the real tests."),
 ("What should the invoice contain?", "Your own name, GST details, and a line for each item naming brand, size, grade and quantity. That invoice is what makes a warranty claim possible and what prevents material bought for your house being billed elsewhere."),
 ("Should I pay in advance?", "There is no need to. Mount Cable works on pay on delivery — the material reaches your site, you inspect and QR-verify it, and only then do you pay, in cash, UPI, card or bank transfer."),
 ("How do I check that a price is honest?", "Get a reference quote for your full list from an established distributor. Genuine electrical runs on thin margins, so quotes from honest sellers cluster within a few percent. A large gap indicates a different product, not a better deal."),
], ("happy-customer-receiving-electrical-order.jpg", "A customer verifying and receiving genuine electrical material at their site")),

"which-switch-brand-should-you-buy": ([
 ("How do I choose a switch brand on a budget?", "Decide the per-point budget first, then pick the best series available within it rather than the best-known brand. A good mid range from a reputable manufacturer outperforms a premium-looking counterfeit or a badly chosen entry range at the same price."),
 ("Is it worth spending more on switches?", "Up to a point. Moving from entry to mid range buys a genuinely better contact material and switch action, which is what determines whether the switch still feels right in five years. Beyond mid range you are mostly buying finish, module variety and design."),
 ("Can I use different switch brands in different rooms?", "You can, but the mounting boxes fitted during wiring commit you to a brand family, and mixing produces visible inconsistency. If budget is the reason, use one brand throughout and vary the series only where the difference will not be seen side by side."),
 ("How many points should I plan for?", "Around 60 to 90 for a 2BHK and 100 to 150 for a 3BHK. Spend any extra points on kitchen sockets and bedside sockets rather than additional light points, which is where people most often wish they had planned better."),
 ("What should I check when the switches arrive?", "Sealed boxes, sharp branding print, clean moulding with no flash, modules that seat flush without force, and a firm consistent switch action across the batch. Check before installation, while the whole delivery is still available for comparison."),
], ("homeowner-electrician-discussing-switchboard.jpg", "A homeowner and electrician choosing switch positions and ranges")),

"which-wire-brand-should-you-buy-for-your-house": ([
 ("Which wire brand should I buy for my house?", "Any of the established brands bought genuine from an authorised source will serve a house for decades. Prefer the brand your electrician is familiar with and your local distributor stocks deeply, so replacements and later extensions are straightforward."),
 ("Does the brand matter more than the grade?", "The grade matters more. Choosing FR or FRLS, and getting the sq mm right for each circuit, affects safety far more than which of the major brands is on the coil. Grade and sizing are decisions you make once and live with for thirty years."),
 ("How much does brand choice change the cost?", "Single-digit percent on comparable grades across the major brands. On a full house that is a small figure next to the effect of the switch range, the point count or getting the size mix wrong."),
 ("Should I let my electrician choose the brand?", "Take his input on which brand he prefers to work with, but buy the material yourself in your own name. His familiarity is genuinely useful; leaving the purchase to him on a with-material basis is where substitution happens."),
 ("How do I make sure what arrives is genuine?", "Order sealed cartons, take a GST invoice listing brand, size and grade for every item, scan the QR on each carton at your site, and pay only after verification. That sequence removes almost all of the risk."),
], ("senior-electrician-teaching-apprentice.jpg", "An experienced electrician explaining wire selection to an apprentice")),

"best-electrical-brands-home-wiring-india": ([
 ("Which electrical brands are best for home wiring in India?", "For wires, the established names all use electrolytic-grade copper to the same IS standards and differ mainly in premium insulation ranges and local availability. For switchgear and switches the differences are larger, and matching the distribution board and MCBs to one brand matters more than the brand chosen."),
 ("Should I use the same brand for wires, switches and switchgear?", "Not necessarily. Wires, modular switches and switchgear are separate decisions and few manufacturers lead in all three. What does matter is keeping the distribution board and its MCBs within one brand family, and keeping switch modules and plates within one series."),
 ("How do I avoid counterfeits across all these categories?", "Buy from an authorised dealer for each brand, insist on sealed packaging, take a GST invoice naming brand, series and specification for every line, and verify by QR at your site before paying. The purchase channel does more work than any visual check."),
 ("Where is it worth spending more?", "Switchgear first, because an MCB or RCCB either works during a fault or does not. Then wire grade and correct sizing. Modular switches are the category where a modest choice is entirely reasonable if the budget is tight."),
 ("How do I compare brands for my own requirement?", "Use the brand selector to narrow the field, the wire price comparison guide for current bands, and then send your list to 88676 76700 for an exact quote across whichever brands you shortlist."),
], ("happy-electrical-contractor-site-team.jpg", "An electrical contractor and his team working with multi-brand material on site")),

}
